[project]
name = "yampr"
version = "0.1.0"
description = "Yet Another MPRIS Discord RPC Client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx",
    "dbus-fast~=2.44.5",
    "pypresence~=4.6.1",
]
